global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Adjunte estas etiquetas a cualquier serie temporal o alerta cuando se comunique con
  # sistemas externos (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Cargue y evalúe las reglas en este archivo cada 'evaluation_interval' en segundos.
rule_files:
  - "alert.rules"

# Una configuracion de Scrape que contiene los Endpoints para recoger los datos
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

