apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  awsElasticBlockStore:
    volumeID: "<EBS-Volume-ID>"
    fsType: ext4
  storageClassName: "ebs-sc"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  storageClassName: "ebs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
