name: Verify Prometheus Configuration

on:
  push:
    branches:
      - main  # Ajusta esto a tu nombre de rama si no es 'main'
  pull_request:
    branches:
      - main  # Ajusta esto a tu nombre de rama si no es 'main'

jobs:
  verify-config-karancode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Prometheus Configuration (karancode)
      uses: docker://ghcr.io/karancode/promtool-github-action:latest
      with:
        args: check config Dockerfiles/monitoring/prometheus/prometheus.yml

  verify-config-promtool-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Prometheus Configuration (promtool-action)
      uses: karancode/promtool-action@main
      with:
        args: check config Dockerfiles/monitoring/prometheus/prometheus.yml

  verify-config-peimanja:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Prometheus Configuration (peimanja)
      uses: peimanja/promtool-github-actions@master
      with:
        args: check config Dockerfiles/monitoring/prometheus/prometheus.yml
