name: Check Prometheus Configurations

on:
  push:
    paths:
    - 'Dockerfiles/monitoring/prometheus/*.yml'
    - 'Dockerfiles/monitoring/prometheus/*.rules'
    - '.github/workflows/prometheus-ci.yml'

jobs:
  on-push:
    name: On Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Check Prometheus Configurations
      uses: peimanja/promtool-github-actions@master
      with:
        promtool_actions_subcommand: 'config'
        promtool_actions_files: 'Dockerfiles/monitoring/prometheus/prometheus.yml'
        promtool_actions_version: '2.41.0'
        promtool_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t my-prometheus -f Dockerfiles/prometheus.Dockerfile .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-prometheus:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'