name: Check Prometheus Configurations

on:
  push:
    paths:
    - 'Dockerfiles/monitoring/prometheus/*.yml'
    - 'Dockerfiles/monitoring/prometheus/*.rules'

jobs:
  on-push:
    name: On Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Check Prometheus Configurations
      uses: peimanja/promtool-github-actions@master
      with:
        promtool_actions_subcommand: 'config'
        promtool_actions_files: 'Dockerfiles/monitoring/prometheus/prometheus.yml'
        promtool_actions_version: '2.41.0'
        promtool_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate Alerting Rules
      uses: peimanja/promtool-github-actions@master
      with:
        promtool_actions_subcommand: 'config'
        promtool_actions_files: 'Dockerfiles/monitoring/prometheus/alert.rules'
        promtool_actions_version: '2.41.0'
        promtool_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
