name: 'Terraform CI'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5

    - name: Terraform Format
      id: fmt
      run: |
        cd terraform
        terraform fmt -check

    - name: Terraform Initialize
      id: init
      run: |
        cd terraform
        terraform init

    - name: Terraform Validate
      id: validate
      run: |
        cd terraform
        terraform validate -no-color

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: |
        cd terraform
        terraform plan -no-color
      continue-on-error: true

    - name: Terraform Security Scan
      id: security
      uses: triat/terraform-security-scan@v3
      with:
        tfsec_version: latest

    # - name: Publish Security Scan Results
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: tfsec-results
    #     path: tfsec-results.txt
