name: 'Terraform CI'

on:
  push:
    branches:
        - main
    paths:
        - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Security Scan
      id: security
      uses: tfsec/tfsec-pr-commenter-action@v0.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Terraform Plan for Pull Requests
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      continue-on-error: true



